function [fitresult, gof] = createFit(indexarr, midMark)
%CREATEFIT(INDEXARR,MIDMARK)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : indexarr
%      Y Output: midMark
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 20-Mar-2017 19:14:37


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( indexarr, midMark );

% Set up fittype and options.
ft = fittype( 'rat41' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.754686681982361 0.276025076998578 0.679702676853675 0.655098003973841 0.162611735194631 0.118997681558377];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'untitled fit 1' );

% Plot fit with data.
subplotfill( 2, 1, 1 );
hold on
set(gca,'fontsize',12);
h = plot( fitresult, xData, yData );
legend( h, 'Data', 'Rational Fit', 'Location', 'SouthEast' );
% Label axes
%xlabel( '% Creepage' );
ylabel( 'F/N (Using Raw Data)' );
grid on
hold off;
removewhitespace;
% Plot residuals.
subplotfill( 2, 1, 2 );
hold on
set(gca,'fontsize',12);
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'residuals', 'Fit Line', 'Location', 'SouthEast' );
% Label axes
xlabel( '% Creepage' );
ylabel( 'Residuals' );
grid on
hold off
removewhitespace;


