function [Sample,WheelX,WheelY,WheelZ,MotorX,MotorY,MotorZ,Axis0CommandVelocitycntssec,Axis0ActualVelocitycntssec,Wx1x2,Wx3x4,Rx1x2,Rx3x4] = importfile2(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [SAMPLE,WHEELX,WHEELY,WHEELZ,MOTORX,MOTORY,MOTORZ,AXIS0COMMANDVELOCITYCNTSSEC,AXIS0ACTUALVELOCITYCNTSSEC,WX1X2,WX3X4,RX1X2,RX3X4]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [SAMPLE,WHEELX,WHEELY,WHEELZ,MOTORX,MOTORY,MOTORZ,AXIS0COMMANDVELOCITYCNTSSEC,AXIS0ACTUALVELOCITYCNTSSEC,WX1X2,WX3X4,RX1X2,RX3X4]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Sample,WheelX,WheelY,WheelZ,MotorX,MotorY,MotorZ,Axis0CommandVelocitycntssec,Axis0ActualVelocitycntssec,Wx1x2,Wx3x4,Rx1x2,Rx3x4] = importfile('RR_6-20-17_1.txt',2001, 12001);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/06/21 15:41:21

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2001;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
Sample = cell2mat(raw(:, 1));
WheelX = cell2mat(raw(:, 2));
WheelY = cell2mat(raw(:, 3));
WheelZ = cell2mat(raw(:, 4));
MotorX = cell2mat(raw(:, 5));
MotorY = cell2mat(raw(:, 6));
MotorZ = cell2mat(raw(:, 7));
Axis0CommandVelocitycntssec = cell2mat(raw(:, 8));
Axis0ActualVelocitycntssec = cell2mat(raw(:, 9));
Wx1x2 = cell2mat(raw(:, 10));
Wx3x4 = cell2mat(raw(:, 11));
Rx1x2 = cell2mat(raw(:, 12));
Rx3x4 = cell2mat(raw(:, 13));


