function [fitresult, gof] = plotfit(fz, fx,lw)
%CREATEFIT1(FZ,FX)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : fz
%      Y Output: fx
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Apr-2017 16:17:22


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( fz, fx );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
%figure( 'Name', 'Causality Fit' );
h = plot( fitresult,'-b', xData, yData,'ko');
set(h,'LineWidth',lw);
%legend( h, 'fx vs. fz', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
%xlabel( 'Normal Forces' );
%ylabel( 'Longitudinal Forces' );
% set(gca,'XTickLabel',[],'YTickLabel',[]); 
legend(gca,'off');
xlabel([]);
ylabel([]);
grid on
box on
removewhitespace;


